### PR TITLE
Fix macOS install instructions with brew

### PR DESCRIPTION
**Pull request by MrBenJ**
Hi! Thanks for making such an awesome project!

I found some issues while installing and building from source for macOS with the brew instructions. I added the fixes in the README.md file.

Hope this helps!

### CODE REVIEW

**Comment by MrBenJ** [comment]
Hi @wereturtle ! I'm sure you're a very busy fellow, but I just wanted to gently remind you and nudge you here about this PR for the README file for macOS users :).

**Comment by HankG** [comment]
I just attempted to build and ran across the same problem and solution.  I didn't realize there was a way to add the stuff to the command line directly with brew link so instead manually editing the bash_profile file to get a successful build.  Following your steps did not work in successfully setting up the environment on my machine.  Also from what I read at [the Brew formula website](https://formulae.brew.sh/formula/qt) the package name is just `qt` now not `qt5`.

**Comment by MrBenJ** [comment]
@HankG - Awesome! Thanks for helping out and validating, I appreciate it.

I'm pretty sure running `qt5` will work just fine. I just ran it on my other machine and it worked just fine. Looking at the link you posted, its says it's `also known as qt5`, so it should work either way.

Screen Shot 2019-06-01 at 12 57 02 PM


How can I help you getting set up on your local? Feel free to post any terminal output so we can get Ghostwriter on your mac :).

**Comment by HankG** [comment]
@MrBenJ oh I'm good and have it running it was about what is the proper way to update the documentation.  I read the above as qt5 works but it's qt now.  Either change would be fine except I would lean towards using the "qt".  However the getting qmake working didn't happen out of the box for me without updating my command line path.  The step you had failed linking one of the libraries and then bombed out.  I can run it in verbose mode and dump the outputs and/or have a second "if this doesn't work step."  Essentially the step is to search the Cellar for the qmake excutable and then update .bash_profile with a standard "echo 'export'" type method.

**Comment by MrBenJ** [comment]
@HankG  - If you can put in a comment the the instructions for manually editing your `.bash_profile`, that'd be great. I'll add it to my PR :).

**Comment by HankG** [comment]
1. Find the path to the `qmake` file in the Homebrew Cellar on your system:
`find /usr/local/Cellar/ -name "qmake"`

2. Add the qmake location to your Bash environment variables (example for Qt 5.12.3):
`echo 'export PATH=/usr/local/Cellar/qt/5.12.3/bin:$PATH' >> ~/.bash_profile`

3. Create a new terminal or source the file to have the path to `qmake` added to the path:
`source ~/.bash_profile`

**Pull request merged**
