### PR TITLE
initial snapcraft.yaml to build a .snap package

### PR DESCRIPTION
**Pull request by thibran**
Added a file to build a ghostwriter [snap package](http://snapcraft.io/docs/).

Tested on: Ubuntu 17.04 dev 64-Bit

The snapcraft.yaml works, but needs more love (not needed files/libs should be removed from the resulting snap). This commit is just to get you started. If you want you could publish the ghostwriter snap to the Ubuntu Store [edge-channel](http://snapcraft.io/docs/build-snaps/publish), to make a snappy-start and see how things go :)

How to build, install and publish a snap:

* Install Snapcraft: `sudo apt install snapcraft`
* Move to the ghostwriter source directory
* Build the snap with: `snapcraft`
* Install the snap locally with: `sudo snap install --force-dangerous ghostwriter_1.4.2_amd64.snap`
* Publish the snap to the [Ubuntu Store](myapps.developer.ubuntu.com)

PS: My motivation was that I read about ghostwriter at OMG Ubuntu and thought, not again an app that needs a PPA! So I build with my moderate snappy knowledge an initial snapcraft.yaml for ghostwriter.

### CODE REVIEW

**Comment by wereturtle** [comment]
Thanks!  I'll have to play around with it when I get some time.

**Comment by battlemidget** [comment]
Why was this closed?

**Comment by wereturtle** [comment]
Somebody already made a snap package that you can download from the Canonical snap repos.  Also, I do not have the energy to maintain both the PPA and the snap package.

**Comment by battlemidget** [comment]
@wereturtle If you pulled in the snapcraft PR linking it up to an automatic build service is easy through build.snapcraft.io and it would happen on each commit.

**Comment by wereturtle** [comment]
As I said, someone apparently stepped up and is maintaining the snap package in the Canonical repo.  It is much better that way.  If I were to do as you say, and if you disappear, then I'm stuck maintaining it for any new dependencies and so on.  I really don't have the time for that.  Sorry.  Your are, of course, welcome to make sure that what is already in the Canonical snap repo remains maintained, and to volunteer for updates to that.

**Pull request closed without merging**
