### PR TITLE
Improved markup behavior (bold/italic/strikethrough)

### PR DESCRIPTION
**Pull request by scottmudge**
## Changes

This improves the behavior of the markup insertion to behave more like a standard word-processor.

### 1. Auto-close Markup Block

If the cursor is at the end of a markup block, but the cursor is **within** the markup block itself, it no longer inserts an extra empty markup block. Instead, the cursor is moved outside the existing markup terminator.

Example:

`This is a block of text **with bolded[CUR]** contents.`

User uses `Ctrl+B`

`This is a block of text **with bolded**[CUR] contents.`

This allows the user to easily start a bold/italic/strikethrough section, write what they would like, then terminate the markup section again with `Ctrl+B` (or whatever), rather than manually having to press the arrow key twice.

### 2. Highlighted/Selected Text Markup Toggling

If the user has selected/highlighted a section of text to toggle a markup style (bold, italic, strike-through), instead of continually adding new markup markers at the start/end of the selected/highlighted block, it will toggle it on and off.

Example (`[text]` is meant to be selected/highlighted):

`This is a block of text *[with italic]* contents.`

User uses `Ctrl+I`

`This is a block of text [with italic] contents.`

### 3. Preventing erroneous extra markup blocks when cursor is immediately after an existing block.

If the user attempts to insert markup while the cursor is already immediately after an existing markup terminator, nothing occurs. This prevents extra markup from being added where it logically wouldn't make sense.

Example:

`This is a block of text **with bolded**[CUR] contents.`

User uses `Ctrl+B`

`This is a block of text **with bolded**[CUR] contents.`

This also works in this instance:

`This is a block of text **[CUR]with bolded** contents.`

### CODE REVIEW

**Comment by scottmudge** [comment]
Edit: pushed another fix to this PR which fixed a pre-existing bug in `ghostwriter` which caused reverse-selected  (Right-to-Left) text to have an invalid selection preserved after markup is inserted.

Current Version -- left-to-right first (no bug), right-to-left second (bug):

ghostwriter_tgBCHslLJn

After Fix:

ghostwriter_S6pDu2UAGu

**Comment by scottmudge** [comment]
Notice: Do not merge just yet, I am working on further improvements.

In addition to the previously mentioned changes, I am also adding what is equivalent to word processors toggling bold/italic/strikethrough of text if the cursor is adjacent to already formatted text. It will then also select the text within the boundaries of the succeeding/preceeding markup block to allow subsequent toggling if desired.

E.g.,

`This is [CUR]**some bolded** text.`

User press `Ctrl+B`

`This is [some bolded] text.`

User press `Ctrl+B` again

`This is **[some bolded]** text.`

Note: `[text]` indicates it is selected/hilighted.

I am still working out some kinks, so wait until my next push.

**Comment by scottmudge** [comment]
Alright, the changes are pretty much done. I've tested them using text at very beginning/end of document, start of new line, end of line, punctuation, and so on. Seems to work in all cases.

Here's a gif:

ghostwriter_pRkTrpJgiM

**Comment by abenson** [comment]
I would recommend [squashing](https://www.git-tower.com/learn/git/faq/git-squash) related commits to make the PR a bit cleaner.  I've been testing the changes as well, I like it and the improvements look good.

**Comment by abenson** [comment]
Ctrl-B followed by Ctrl-I behaves weird.  Cursor ends up `***_*` there.  Ctrl-I followed by Ctrl-B works correctly, with the cursor ending up at the expected position. `***_***`

**Comment by scottmudge** [comment]
Hmm might have to add some special logic for that particular case. Unfortunately there aren't unique tags for italic vs bold, so it's just counting asterisks. 

Too bad underscores don't work within a word, otherwise it would be possible to distinguish the two with asterisks vs underscores.

Yeah I'll need to squash the commits down, but the Files Changed tab kinda does the job for now.

Thanks for testing though!

**Comment by scottmudge** [comment]
Alright, refactored it a bit more. Behavior is more flexible now and accounts for more edge cases. @abenson The bugs you noted should now be fixed.

Also squashed it down into one commit.

**Comment by scottmudge** [comment]
Alright, one more update to wrap things up. Refined some logic to account for cases where there are adjacent/nearby markup blocks with the same markup strings. Preference toward which direction to pair up markup terminators is now determined by adjacent spaces and punctuation, similar to how the existing markup block coloring works.

**Comment by wereturtle** [comment]
OK I don't normally take pull requests for code changes, but since (a) you seem to have done a thorough job and (b) someone else volunteered to check out your changes and help find the bugs first, I'll go ahead and merge it.  The two of you working together have given me the idea of maybe updating my pull request policy to approve if 1 or 2 people test it and give it a thumbs up.  Thank you both!

**Pull request merged**
