### PR TITLE
Italian Translation

### PR DESCRIPTION
**Pull request by tajmone**
Translation into Italian completed with Qt Linguist.

I've included the Italian localization "`.ts`" file, as well as the "Released" "`.qm`" file. Please note that I don't have the full Qt suite on my PC, I've just downloaded the Qt Linguist tool to carry out the translation, and I didn't have a chance to test it live, nor I am sure about the "release" file I've added ("`.qm`" file) — but since the Release option was standing out on the menu, I though to just try it.

I've changed filename so it ends in "`_it-IT`", following on the example of the Portoguese translation. ("`_it`" might have sufficed, but officially there is a distinction in localization between Italian-Italian and Swiss-Italian!)

Translation should be 100% ok. I've added lots of translator notes, to keep track of which string appears where, and also noted down doubts about possible choices of words, or the reasons for certain choices, along with warnings to keep an eye for checking the length of some strings how they will show up in the compiled app.

### CODE REVIEW

**Comment by tajmone** [comment]
NOTE: I've just discovere that the files should be renamed:

`ghostwriter_it-IT.qm` to `ghostwriter_it.qm`

`ghostwriter_it-IT.ts` to `ghostwriter_it.ts`

Seems that Qt doesn't follow standard naming conventions for i18n!

**Comment by tajmone** [comment]
Ok, I've fixed a couple of things:

- removed the binary `.qm` file
- renamed the translation file to `ghostwriter_it.ts` (instead of `_it-IT`)
- fixed a couple of typos, and improved some strings

I wasn't sure if the .qm translation file was needed or not. I can create it from within Qt Linguist, via the "Release" option, and if I place it in the `translations` folder of ghostwriter it works. But I guess that when someone builds the app from scratch the translation files will be automatically compiled. 

Just to be on safe side, let me know if in future updates I should upload it or not (in case not, I'll add a `.gitignore` file in the `translations` folder).

**Comment by wereturtle** [comment]
Try `_it_IT` instead of `_it-IT` (use underscore instead of hyphen).

**Comment by tajmone** [comment]
Confirmed: `it_IT` works fine!

**Pull request merged**
