### PR TITLE
Update Italian Translation to 1.6.0

### PR DESCRIPTION
**Pull request by tajmone**
Italian translation updated, as of #294.

### CODE REVIEW

**Comment by dbelyaev** [comment]
@tajmone did you try to run **lupdate** on italian ts file in order to get it sync with string in source code? It looks strange that you only got a few strings to translate.

**Comment by tajmone** [comment]
> did you try to run lupdate on italian ts file in order to get it sync with strings in source code? It looks strange that you only got a few strings to translate.

On my machine I have only QT Linguist (GUI) installed, and don't have the command line Qt tools like lupdate.

In the previous updates I didn't face any problems in the workflow: just opened "`ghostwriter_it.ts`" in Linguist, and it would show the unfinished strings. But this time the unfinished strings were just 3 in total.

Something doesn't seem right, but I don't see any update options in Linguist's menu.

**Comment by tajmone** [comment]
I've copied and reponed the original Italian file from `master` branch, to check again. I confirm: there are only 2 non translated strings!

Either some missing string entries were automatically set with Linquist's suggested translations, or the Italian file `ghostwriter_it.ts` is not up to date with the english reference `ghostwriter_en.qm`.

Due to having only Qt Linguist installed (not the whole Qt package), I can't update the Italian file myself. If I remember correctly, with the previous updates I had to ask @wereturtle to update the italian file via `lupdate`, because of this problem.

I have Linguist v4.6 — I remember that there were reasons why I'm using this version, at the time I set it up I looked into it and, if I remember correctly, there were problems with installing Linguist v5.6 separately from the whole Qt package, and anyhow they work in a compatible manner.

**Comment by tajmone** [comment]
I've checked, and I confirm that I need someonw to run lupdate for me, so I can get the update Italian file. This was how I handled it in the past.

I can't install Qt creator 5 on my system because it would conflict with other Qt 4 apps I have installed — also, I don't need Qt at all, just Qt Linguist.

Qt website doesn't offer any longer full offline installers downloads (not even to registered users), so I can't get hold of just lupdate tool.

**Comment by dbelyaev** [comment]
@tajmone I'll do this for you. Usually maintainer updates all the ts files before release to have them updated and synced with changes in code base.

**Comment by dbelyaev** [comment]
@tajmone I did `lupdate` on codebase from your branch (`i18n-IT-update-1.6.0`) and got those as output:
```
Updating 'translations/ghostwriter_it.ts'...
    Found 330 source text(s) (24 new and 306 already existing)
    Kept 18 obsolete entries
    Number heuristic provided 1 translation(s)
    Same-text heuristic provided 5 translation(s)
```
So now it should have some untranslated strings. There is a PR from my fork of `ghostwriter` repo to your i18n branch, please review and merge

**Comment by tajmone** [comment]
Now the translation is ready. Thanks to @dbelyaev for helping me out with lupdate!

I've taken the chance to revise the full text:

- minor typos fixed
- adopted better title casing convention (before all menu entries titles where capitalized the American way, now I kept only the first word capitalized, it looks neater and is more common in Italian)

**Pull request merged**
