### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by suhr**
I'm going to start translating ghostwriter in russian, but I need some help to make it work.

At this moment ghostwriter lacks an option to chose the UI language.

### CODE REVIEW

**Comment by wereturtle** [comment]
I updated the application to lookup the translation file to load based on the current locale settings.  So if your OS locale is set to Russian, ghostwriter will look for the Russian translation file in the "translations" folder.  Put this folder in the same directory as your ghostwriter executable for testing purposes.  (I have it looking for the translations folder in several locations, but this one is the most expedient for your purposes.)

You should also rerun the lupdate tool, since I changed a settings option name (from "Languages..." to "Dictionaries...") to avoid confusion as to what the option does.

Thanks in advance for doing this.  I really appreciate it!  :)

**Comment by suhr** [comment]
One important thing:

> wordCountLabel->setText(QString("0 ") + tr("words"));

Here [plural forms](http://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals) should be used.

**Comment by wereturtle** [comment]
Thanks for catching that.  I have updated it for the plural forms.

**Comment by suhr** [comment]
There's a lot of untranslatable things like `tr("    ")`, `tr("\n")` or `tr("border-image: url(%1) 0 0 0 0 stretch stretch; ")`.

Consider removing `tr` from these places.

**Comment by tajmone** [comment]
I've just added Italian translation files in a Pull Request, but will join conversation here since the topic is along the same lines.

Maybe the contribution section of the README should say a bit more on how to contribute with translations.

-  Finding Qt Linguist wasn't exactly a piece of cake — it's currently hosted on Google Code, but not linked in evidence on Qt site.

- I wasn't sure if I should name the translation file as "`_it-IT`" or just "_it" (conventionally,  "`_it-IT`" is preferred in order to distinguish Italian-Italian from Swiss-Italian!).

- Not having the full Qt suite I had problems figuring out if I had to also "Release" (the `.qm` file) or if just the `.ts` file would do...

- I've tried putting the localization files (both `.qm` and `.ts`) in the `\data\translations\` folder (of Portable version), along with the pre-existing English file. But restarting the app didn't show Italian dialogs.

- I've renamed the file from `ghostwriter_it-IT.qm` to `ghostwriter_it.qm`, and it worked — now I can see the dialogs in Italian! So, the naming format should follow the two-letters convention.

- So, a bit more info on the translation process might encourage translators (especially the faint-of-heart types), and a direct link to Qt Linguist also. Qt online documentation for translators didn't provide to be of much use: too techinical, and didn't mention basic things like naming conventions.

- Also, it seems that now that I have the Italian localization files inside the Data folder, ghostwriter enforces Italian on my UI. Mhhh, I think some preferences aught to be in place, allowing users to choose the language. Personally, I always tend to use English for UI because it allows getting confident with the terminology that I'll find in the various docs and tutorials.

If I may rant a bit ... Geeeee! That Qt Linguist app has such a small and hugly font, and no options to change it, nor its size! It's so small that I had to use a magnifying glass to double-check what I wrote! Very straining for the eyes. One would thing that an app for translators would take into first-consideration things relating to usability: font-size, colors, contrast, ecc.

**Comment by suhr** [comment]
> Not having the full Qt suite I had problems figuring out if I had to also "Release" (the .qm file) or if just the .ts file would do...

`.qm` files should be generated by `qmake`. As a general rule, you should not add binary files into git repo if they're not really necessary.

> I've tried putting the localization files (both .qm and .ts) in the \data\translations\ folder (of Portable version), along with the pre-existing English file. But restarting the app didn't show Italian dialogs.

Currently ghostwriter searches for translations in the current directory.

> Geeeee! That Qt Linguist app has such a small and hugly font, and no options to change it, nor its size!

Looks like Qt related issue, it should use the default font size AFAIK.

> Maybe the contribution section of the README should say a bit more on how to contribute with translations.

I think so.

**Comment by tajmone** [comment]
What you mean by:

> Currently ghostwriter searches for translations in the current directory.

The directory of its main binary executable?

And using which version (installed/portable) and which OS?

I've solved it by putting the translation file inside ` \data\translations\` folder, because that's where I noticed there was a `ghostwriter_en.qm` file. But I'm using the Portable version, so all setting files are kept within the directory structure of the main executable. An that's on Windows OS, so I'm not sure how fully installed version look for files, and difference in operating systems when it comes to looking for preference files around.

It seems that the binary qm file generated by Qt Linguist worked fine (note: it's an old app, possibly from the pre-Qt5 age, so I wasn't sure if it would "release" it the right way. But it did.)

**Comment by suhr** [comment]
> The directory of its main binary executable?

The directory you run ghostwriter from aka [working directory](https://en.wikipedia.org/wiki/Working_directory).

> And using which version (installed/portable) and which OS?

I'm using Linux, but it should work for other OSes too.

**Comment by suhr** [comment]
Hey, it's not complete!

**Comment by wereturtle** [comment]
Oops!  Oh well.  Go ahead and put in another pull request whenever you're finished.  I promise I won't package the next release without it.  In the meantime, I suppose halfway might be better than none at all for some people?

**Comment by suhr** [comment]
> I suppose halfway might be better than none at all for some people?

Well, there're things that *should* be translated (menus and HUDs).

**Comment by tajmone** [comment]
Shouldn't be a problem though. Future updates ghostwriter will introduce some new strings not covered by present translations, thus rendering all existing full translation into "incomplete" ones. But wherever there is lack of correspondent translation it should rely on the English source as a base-reference.

What today is a 100% translation, in 6 monthes times might become a 80%, and so on. Still, 80% is better than no translation. As long as the main menu entries and labels are covered, users should work their way through the GUI.

**Pull request merged**
