### PR TITLE
Italian 1 4 0

### PR DESCRIPTION
**Pull request by tajmone**
Updated Italian translation file, for GW 1.4.0

### CODE REVIEW

**Comment by wereturtle** [comment]
Hi Tristano,

Thanks for the quick turnaround.

There seem to be a lot of merge conflicts, plus missing translations. I don't think you were working with the latest that is on the master branch.

If it's not too much trouble, would you mind doing a fresh git pull from your local master branch? Alternatively, you can just grab the .ts file off the GitHub page and update it, and then attach it in a message on this thread. I can hand merge if need be.

Thanks!

P.S. Don't worry, there's plenty of time to get this done!

**Comment by tajmone** [comment]
Re: [wereturtle/ghostwriter] Italian 1 4 0 (#87)


Hello wereturtle,

Strange, it should have been updated ... I went through the usual process of updating from your repo. 

Maybe I've missed some passage, due to tireness. I'll look into it again!

Tristano

Monday, June 6, 2016, 12:03:30 AM, you wrote:





Hi Tristano,
Thanks for the quick turnaround.
There seem to be a lot of merge conflicts, plus missing translations. I don't think you were working with the latest that is on the master branch.
If it's not too much trouble, would you mind doing a fresh git pull from your local master branch? Alternatively, you can just grab the .ts file off the GitHub page and update it, and then attach it in a message on this thread. I can hand merge if need be.
Thanks!
P.S. Don't worry, there's plenty of time to get this done!
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.





-- 
Best regards,
 Tristano                            mailto:tajmone@gmail.com

**Comment by tajmone** [comment]
Ok @wereturtle, you were right: something went wrong when I updated my local repo -- don't ask me why; but now it seems fixed.

I confirm, there were quite a lot more terms in need of translation then in the previous pull request.

So, now all shall be fine...

PS: I had to improvise for LIX and CLI reading indexes — haven't found any mention of them in Italian, so I just mention them as "Readability Indexed" LIX and CLI.

The rest seems all fine...

**Comment by tajmone** [comment]
Mhhh something doesn't seem right, still conflicts. I'll try to make an independet pull request, past this one...

**Pull request closed without merging**
